### PR TITLE
mac osx build fixes for alloca et al

### LINKED ISSUE #181: Won't build on Mac OS X Monterey
```
Building with:
  Version string:  unknown
  Architecture:    x86_64
  DSP mix:         x86
  RTLSDR support:  yes
  BladeRF support: no
  HackRF support:  no
  LimeSDR support: no
cc  -I. -D_POSIX_C_SOURCE=200112L -DMODES_DUMP1090_VERSION=\"unknown\" -DMODES_DUMP1090_VARIANT=\"dump1090-fa\" -DMISSING_NANOSLEEP -DENABLE_CPUFEATURES -Icpu_features/include -DENABLE_RTLSDR -DSTARCH_MIX_X86 -O3 -g -std=c11 -fno-common -Wall -Wmissing-declarations -Werror -W -I/usr/local/Cellar/librtlsdr/0.6.0/include/ -I/usr/local/Cellar/libusb/1.0.24/include/libusb-1.0 -c net_io.c -o net_io.o
net_io.c:1086:15: error: implicit declaration of function 'alloca' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    buf = p = alloca(len);
              ^
net_io.c:1086:13: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
    buf = p = alloca(len);
            ^ ~~~~~~~~~~~
2 errors generated.
make: *** [net_io.o] Error 1
```

### PR DESCRIPTION
**Pull request by mutability**
Should fix #181

### CODE REVIEW

File: dump1090.h [hunk 1]
```diff
@@ -79,6 +79,7 @@
 #include <sys/ioctl.h>
 #include <time.h>
 #include <limits.h>
+#include <strings.h>
```
Comment (bovine) [inline dump1090.h:82]: What needs strings.h? malloc and free are in stdlib.h

Comment (bovine) [reply dump1090.h:82]: nm, strcasecmp
